[theme]
# Detalles activos y botones en un verde más claro y vivo
primaryColor = "#2ECC71"

# Fondo de la aplicación (Marfil suave muy elegante)
backgroundColor = "#FDFBF7"

# El fondo del menú lateral (Verde corporativo limpio)
secondaryBackgroundColor = "#27AE60"

# Texto principal de la app en gris oscuro
textColor = "#2C3E50"

font = "sans serif"
